[I 2025-07-16 09:12:30.135 ServerApp] Extension package jupyter_lsp took 0.3486s to import
[I 2025-07-16 09:12:30.247 ServerApp] Extension package jupyter_server_terminals took 0.1109s to import
[I 2025-07-16 09:12:32.169 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-16 09:12:32.184 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-16 09:12:32.200 ServerApp] jupyterlab | extension was successfully linked.
[I 2025-07-16 09:12:32.215 ServerApp] notebook | extension was successfully linked.
[I 2025-07-16 09:12:35.503 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-16 09:12:35.720 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-16 09:12:35.726 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-16 09:12:35.729 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-16 09:12:35.751 LabApp] JupyterLab extension loaded from /home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyterlab
[I 2025-07-16 09:12:35.751 LabApp] JupyterLab application directory is /home/bahaduri/.conda/envs/viper2/share/jupyter/lab
[I 2025-07-16 09:12:35.752 LabApp] Extension Manager is 'pypi'.
[I 2025-07-16 09:12:35.803 LabApp] Extensions will be fetched using proxy, proxy host and port: ('192.168.0.100', '3128')
[I 2025-07-16 09:12:35.810 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-16 09:12:35.821 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-16 09:12:35.822 ServerApp] Serving notebooks from local directory: /home/bahaduri/VIPER
[I 2025-07-16 09:12:35.822 ServerApp] Jupyter Server 2.16.0 is running at:
[I 2025-07-16 09:12:35.822 ServerApp] http://pascal:12356/tree?token=6bde8bad7bf167bdb56d55be867023af2b66bdc3ee91e296
[I 2025-07-16 09:12:35.822 ServerApp]     http://127.0.0.1:12356/tree?token=6bde8bad7bf167bdb56d55be867023af2b66bdc3ee91e296
[I 2025-07-16 09:12:35.822 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2025-07-16 09:12:35.842 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/bahaduri/.local/share/jupyter/runtime/jpserver-2223515-open.html
    Or copy and paste one of these URLs:
        http://pascal:12356/tree?token=6bde8bad7bf167bdb56d55be867023af2b66bdc3ee91e296
        http://127.0.0.1:12356/tree?token=6bde8bad7bf167bdb56d55be867023af2b66bdc3ee91e296
[I 2025-07-16 09:12:36.200 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2025-07-16 09:13:16.496 ServerApp] 302 GET / (@192.168.0.100) 1.22ms
[W 2025-07-16 09:13:25.976 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4?1752650005016 (192.168.0.100): Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4
[W 2025-07-16 09:13:25.977 ServerApp] wrote error: 'Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4'
    Traceback (most recent call last):
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/tornado/web.py", line 1848, in _execute
        result = await result
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 508, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 539, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4)
[W 2025-07-16 09:13:26.032 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4?1752650005016 (9041155e72424376b40de8879e3b2b67@192.168.0.100) 87.51ms referer=http://localhost:8000/notebooks/Results_analysis(1).ipynb
[W 2025-07-16 09:13:26.368 ServerApp] Notebook Results_analysis(1).ipynb is not trusted
[W 2025-07-16 09:13:27.314 ServerApp] Notebook Results_analysis(1).ipynb is not trusted
[W 2025-07-16 09:13:27.385 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4/channels?session_id=84997854-cdbe-477d-b387-1a5ffb4eba8a (192.168.0.100): Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4
[W 2025-07-16 09:13:27.479 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4/channels?session_id=84997854-cdbe-477d-b387-1a5ffb4eba8a (9041155e72424376b40de8879e3b2b67@192.168.0.100) 113.17ms referer=None
[W 2025-07-16 09:13:27.516 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4?1752650007348 (192.168.0.100): Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4
[W 2025-07-16 09:13:27.516 ServerApp] wrote error: 'Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4'
    Traceback (most recent call last):
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/tornado/web.py", line 1848, in _execute
        result = await result
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 508, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 539, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4)
[W 2025-07-16 09:13:27.517 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4?1752650007348 (9041155e72424376b40de8879e3b2b67@192.168.0.100) 3.74ms referer=http://localhost:8000/notebooks/Results_analysis(1).ipynb
[I 2025-07-16 09:13:28.528 ServerApp] Kernel started: 236c0ea7-9bf9-45fb-aff1-4882d0a01493
[I 2025-07-16 09:13:30.583 ServerApp] Connecting to kernel 236c0ea7-9bf9-45fb-aff1-4882d0a01493.
[I 2025-07-16 09:13:30.586 ServerApp] Connecting to kernel 236c0ea7-9bf9-45fb-aff1-4882d0a01493.
[W 2025-07-16 09:13:30.588 ServerApp] The websocket_ping_timeout (90000) cannot be longer than the websocket_ping_interval (30000).
    Setting websocket_ping_timeout=30000
[W 2025-07-16 09:13:30.822 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4/channels?session_id=84997854-cdbe-477d-b387-1a5ffb4eba8a (192.168.0.100): Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4
[W 2025-07-16 09:13:30.823 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4/channels?session_id=84997854-cdbe-477d-b387-1a5ffb4eba8a (9041155e72424376b40de8879e3b2b67@192.168.0.100) 4.83ms referer=None
[I 2025-07-16 09:13:30.825 ServerApp] Connecting to kernel 236c0ea7-9bf9-45fb-aff1-4882d0a01493.
[W 2025-07-16 09:13:30.853 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4?1752650010667 (192.168.0.100): Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4
[W 2025-07-16 09:13:30.854 ServerApp] wrote error: 'Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4'
    Traceback (most recent call last):
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/tornado/web.py", line 1848, in _execute
        result = await result
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 508, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 539, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4)
[W 2025-07-16 09:13:30.855 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4?1752650010667 (9041155e72424376b40de8879e3b2b67@192.168.0.100) 4.96ms referer=http://localhost:8000/notebooks/Results_analysis(1).ipynb
[W 2025-07-16 09:13:36.200 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4/channels?session_id=84997854-cdbe-477d-b387-1a5ffb4eba8a (192.168.0.100): Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4
[W 2025-07-16 09:13:36.202 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4/channels?session_id=84997854-cdbe-477d-b387-1a5ffb4eba8a (9041155e72424376b40de8879e3b2b67@192.168.0.100) 2.62ms referer=None
[W 2025-07-16 09:13:36.212 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4?1752650016048 (192.168.0.100): Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4
[W 2025-07-16 09:13:36.213 ServerApp] wrote error: 'Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4'
    Traceback (most recent call last):
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/tornado/web.py", line 1848, in _execute
        result = await result
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 508, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 539, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4)
[W 2025-07-16 09:13:36.214 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4?1752650016048 (9041155e72424376b40de8879e3b2b67@192.168.0.100) 1.99ms referer=http://localhost:8000/notebooks/Results_analysis(1).ipynb
[W 2025-07-16 09:13:49.222 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4/channels?session_id=84997854-cdbe-477d-b387-1a5ffb4eba8a (192.168.0.100): Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4
[W 2025-07-16 09:13:49.223 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4/channels?session_id=84997854-cdbe-477d-b387-1a5ffb4eba8a (9041155e72424376b40de8879e3b2b67@192.168.0.100) 1.90ms referer=None
[W 2025-07-16 09:13:49.232 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4?1752650029068 (192.168.0.100): Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4
[W 2025-07-16 09:13:49.232 ServerApp] wrote error: 'Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4'
    Traceback (most recent call last):
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/tornado/web.py", line 1848, in _execute
        result = await result
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 508, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 539, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4)
[W 2025-07-16 09:13:49.233 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4?1752650029068 (9041155e72424376b40de8879e3b2b67@192.168.0.100) 1.07ms referer=http://localhost:8000/notebooks/Results_analysis(1).ipynb
[W 2025-07-16 09:13:58.179 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4/channels?session_id=84997854-cdbe-477d-b387-1a5ffb4eba8a (192.168.0.100): Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4
[W 2025-07-16 09:13:58.181 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4/channels?session_id=84997854-cdbe-477d-b387-1a5ffb4eba8a (9041155e72424376b40de8879e3b2b67@192.168.0.100) 3.10ms referer=None
[W 2025-07-16 09:13:58.196 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4?1752650038029 (192.168.0.100): Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4
[W 2025-07-16 09:13:58.196 ServerApp] wrote error: 'Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4'
    Traceback (most recent call last):
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/tornado/web.py", line 1848, in _execute
        result = await result
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 508, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 539, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4)
[W 2025-07-16 09:13:58.197 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4?1752650038029 (9041155e72424376b40de8879e3b2b67@192.168.0.100) 2.32ms referer=http://localhost:8000/notebooks/Results_analysis(1).ipynb
[W 2025-07-16 09:14:00.192 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4/channels?session_id=84997854-cdbe-477d-b387-1a5ffb4eba8a (192.168.0.100): Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4
[W 2025-07-16 09:14:00.194 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4/channels?session_id=84997854-cdbe-477d-b387-1a5ffb4eba8a (9041155e72424376b40de8879e3b2b67@192.168.0.100) 2.06ms referer=None
[W 2025-07-16 09:14:00.207 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4?1752650040038 (192.168.0.100): Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4
[W 2025-07-16 09:14:00.208 ServerApp] wrote error: 'Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4'
    Traceback (most recent call last):
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/tornado/web.py", line 1848, in _execute
        result = await result
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 508, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/bahaduri/.conda/envs/viper2/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 539, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: eab3b59f-0896-4f1d-acbf-b44a1230aac4)
[W 2025-07-16 09:14:00.208 ServerApp] 404 GET /api/kernels/eab3b59f-0896-4f1d-acbf-b44a1230aac4?1752650040038 (9041155e72424376b40de8879e3b2b67@192.168.0.100) 1.90ms referer=http://localhost:8000/notebooks/Results_analysis(1).ipynb
[I 2025-07-16 09:15:28.476 ServerApp] Saving file at /Results_analysis(1).ipynb
[W 2025-07-16 09:15:28.478 ServerApp] Notebook Results_analysis(1).ipynb is not trusted
[I 2025-07-16 09:17:29.347 ServerApp] Saving file at /Results_analysis(1).ipynb
[W 2025-07-16 09:17:29.351 ServerApp] Notebook Results_analysis(1).ipynb is not trusted
[I 2025-07-16 09:19:30.205 ServerApp] Saving file at /Results_analysis(1).ipynb
[W 2025-07-16 09:19:30.209 ServerApp] Notebook Results_analysis(1).ipynb is not trusted
[I 2025-07-16 09:42:36.536 ServerApp] Saving file at /Results_analysis(1).ipynb
[W 2025-07-16 09:42:36.539 ServerApp] Notebook Results_analysis(1).ipynb is not trusted
slurmstepd-pascal: error: *** JOB 316662 ON pascal CANCELLED AT 2025-07-16T11:12:36 DUE TO TIME LIMIT ***
